### ISSUE TITLE
macOS  运行闪退

### ISSUE THREAD

**Issue by Maecenas** [chroming/pdfdir#1]
运行打包的程序和源码闪退，错误代码如下：

```
$ python run_gui.py
~/anaconda/lib/python3.5/re.py:203: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)
Traceback (most recent call last):
  File "/pdfdir/gui/main.py", line 75, in export_pdf
    new_path = add_directory(*self._get_args())
  File "/pdfdir/src/pdfdirectory.py", line 9, in add_directory
    return add_bookmark(pdf_path, index_dict)
  File "/pdfdir/pdf/bookmark.py", line 30, in add_bookmark
    pdf = Pdf(path)
  File "/pdfdir/pdf/api.py", line 45, in __init__
    self.writer.addMetadata(reader.getDocumentInfo())
  File "~/anaconda/lib/python3.5/site-packages/PyPDF2/pdf.py", line 538, in addMetadata
    args[NameObject(key)] = createStringObject(value)
  File "~/anaconda/lib/python3.5/site-packages/PyPDF2/generic.py", line 300, in createStringObject
    raise TypeError("createStringObject should have str or unicode arg")
TypeError: createStringObject should have str or unicode arg
Abort trap: 6
```

系统版本：macOS Sierra(10.12.6)

**Comment by chroming** [comment]
我本地 mac 无法重现这个问题，怀疑跟你处理的 pdf有关，你可以试试其他 pdf 文件 看是否会报这个错误

**Comment by Maecenas** [comment]
我试了好几个pdf文件都不行，直到试了一个很简单的pdf成功了，但是目录最后一行没有匹配，最后报错信息是“文件未解密”，但是我也没发现文件有加密的情况。看了一下代码也没看出问题来......

[Getting Started.pdf](https://github.com/chroming/pdfdir/files/1253596/Getting.Started.pdf)
```
$ python run_gui.py
~/anaconda/lib/python3.5/re.py:203: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]
Traceback (most recent call last):
  File "~/anaconda/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1147, in getNumPages
    self.decrypt('')
  File "~/anaconda/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1987, in decrypt
    return self._decrypt(password)
  File "~/anaconda/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1996, in _decrypt
    raise NotImplementedError("only algorithm code 1 and 2 are supported")
NotImplementedError: only algorithm code 1 and 2 are supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pdfdir/gui/main.py", line 75, in export_pdf
    new_path = add_directory(*self._get_args())
  File "/pdfdir/src/pdfdirectory.py", line 9, in add_directory
    return add_bookmark(pdf_path, index_dict)
  File "/pdfdir/pdf/bookmark.py", line 30, in add_bookmark
    pdf = Pdf(path)
  File "~/Documents/Github/pdfdir/pdf/api.py", line 44, in __init__
    self.writer.appendPagesFromReader(reader)
  File "~/anaconda/lib/python3.5/site-packages/PyPDF2/pdf.py", line 343, in appendPagesFromReader
    reader_num_pages = reader.getNumPages()
  File "~/anaconda/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1150, in getNumPages
    raise utils.PdfReadError("File has not been decrypted")
PyPDF2.utils.PdfReadError: File has not been decrypted
Abort trap: 6
```
@chroming

**Comment by chroming** [comment]
最后一行没有匹配是个bug，下个版本会解决。
Getting Started.pdf 这个文件在本地测试也是正常的……

**Comment by Maecenas** [comment]
不好意思传错了......我只有 Getting Started.pdf 这个文件能处理成功，不过一样有两行提示：
```~/anaconda3/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)```

运行失败的文件比如这个
[2016 CHI Workshop HCML.pdf](https://github.com/chroming/pdfdir/files/1254394/2016.CHI.Workshop.HCML.pdf)

**Comment by chroming** [comment]
return _compile(pattern, flags).split(string, maxsplit) 这个报错是个warning没啥关系。

"TypeError: createStringObject should have str or unicode arg" 错误原因找到了，是pdf的metadata中包含一个特殊的 "AAPL#3AKeywords:[""] " 信息导致类型无法匹配。已更新源码处理这类情况，你可以用最新的源码运行试试。

**Comment by Maecenas** [comment]
运行正常，非常感谢！但是还有一点小问题，我发现增加目录后 pdf 文件变小了，不知道其他会有什么后果吗？另外如果输入的页码超过文件的页数，程序也会闪退。
[Getting.Started.Dropbox_new.pdf](https://github.com/chroming/pdfdir/files/1254476/Getting.Started.Dropbox_new.pdf)

**Comment by chroming** [comment]
pdf变小可能是某些metadata没复制过去导致的，如果只是看内容的话内容没减少就行。
输入页码超过页数的情况没做处理，之后的版本会处理的，感谢反馈。

**Comment by Maecenas** [comment]
感觉 readme 里面的「书签」、「导航书签」、「目录」、「大纲」中文用词概念比较含糊，和 Bookmarks、Table of Contents 对应起来会不会比较好呢？

**Comment by chroming** [comment]
对应起来的话就是书签，目录两个词了。目录还容易理解，书签就不容易一眼看出是目录的书签了。大纲这个词我没怎么用过，不知道普通人看到能不能理解
