### ISSUE TITLE
 Object 11 0 not defined.

### ISSUE THREAD

**Issue by bibichuan** [chroming/pdfdir#3]
通过python3执行，目录里面什么都不写也会报错，写了也会报错
/usr/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)
PdfReadWarning: Object 11 0 not defined. [pdf.py:1629]
Traceback (most recent call last):
  File "/home/deepindh/Code/python/pdfdir/src/gui/main.py", line 157, in export_pdf
    new_path = add_directory(*self._get_args())
  File "/home/deepindh/Code/python/pdfdir/src/pdfdirectory.py", line 9, in add_directory
    return add_bookmark(pdf_path, index_dict)
  File "/home/deepindh/Code/python/pdfdir/src/pdf/bookmark.py", line 36, in add_bookmark
    return pdf.save_pdf()
  File "/home/deepindh/Code/python/pdfdir/src/pdf/api.py", line 70, in save_pdf
    self.writer.write(out)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/home/deepindh/.local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1631, in getObject
    raise utils.PdfReadError("Could not find object.")
PyPDF2.utils.PdfReadError: Could not find object.
已放弃

**Comment by chroming** [comment]
抱歉，我没新开分支更新代码，所以源码运行可能出现无法正常运行的情况😂等我近期有空了更新一个稳定版然后新开个稳定版分支
