### ISSUE TITLE
[Bug] 缺少 `config.ini` 文件时导致程序运行错误（自 v0.3.0-beta22 版本起）

### ISSUE THREAD

**Issue by GabrielxDuO** [chroming/pdfdir#40]
#### 背景信息

在下载使用 [Release v0.3.0-beta25](https://github.com/chroming/pdfdir/releases/tag/v0.3.0-beta25) 版本时，直接运行 `pdfdir.exe` 后发生错误。

#### 复现步骤

1. 下载并运行 [Release v0.3.0-beta22](https://github.com/chroming/pdfdir/releases/tag/v0.3.0-beta22) 或更高版本的单文件可执行文件 `pdfdir.exe`。
2. 观察程序是否能正常启动。

#### 预期结果

程序应该能正常启动，即使 `config.ini` 文件不存在，程序也应有默认配置或自动创建该文件。

#### 实际结果

程序在没有 `config.ini` 文件的情况下运行会出现如下错误：

```plaintext
Traceback (most recent call last):
  File "run_gui.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\gui\main.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\config.py", line 19, in <module>
  File "src\config.py", line 29, in Config
  File "configparser.py", line 965, in __getitem__
KeyError: 'LEVEL'
```

#### 影响范围
[Release v0.3.0-beta22](https://github.com/chroming/pdfdir/releases/tag/v0.3.0-beta22) 及更高版本

#### 相关链接

- 5d1216bf76134144abea2275a08c8f9b81d26e1e 

#### 解决方案建议

在 `src/config.py` 中，添加检查 `config.ini` 文件是否存在的逻辑。如果文件不存在，创建文件并填入默认配置。此外，确保读取配置时有合理的默认值，例如：

```python
from configparser import ConfigParser
import os

RE_DICT = {
    'level0': {
        '第1章': '第\d章',
    },

    'level1': {
        '1.1': '\d\.\d',
        '第1节': '第\d节',
    },
    'level2': {
        '1.1.1': '\d\.\d\.\d',
    }

}


class Config(object):
    APP_NAME = 'PDFDir'
    VERSION = 'v0.3.0-beta25'
    WINDOW_ICON = 'pdf.ico'
    HOME_PAGE_URL = 'https://github.com/chroming/pdfdir'
    HELP_PAGE_URL = 'https://github.com/chroming/pdfdir/blob/master/readme.md'
    RELEASE_PAGE_URL = 'https://github.com/chroming/pdfdir/releases'

    cp = ConfigParser()
    config_file = 'config.ini'
    
    # 检查 config.ini 文件是否存在
    if not os.path.exists(config_file):
        with open(config_file, 'w') as configfile:
            cp['LEVEL'] = {'selected_level': '0'}
            cp.write(configfile)
    
    cp.read(config_file, encoding='utf-8')
    SELECTED_LEVEL = cp.get('LEVEL', 'selected_level', fallback='0')

CONFIG = Config()
```

这样修改后，即使 `config.ini` 文件不存在，程序也能正常运行并使用默认配置。

**Comment by chroming** [comment]
感谢反馈以及提供修复建议！这个版本已经添加了这个修改
https://github.com/chroming/pdfdir/releases/tag/v0.3.0-beta26

**Comment by GabrielxDuO** [comment]
> 感谢反馈以及提供修复建议！这个版本已经添加了这个修改 https://github.com/chroming/pdfdir/releases/tag/v0.3.0-beta26

感谢您的及时回复和更新！我已经测试了新版本，问题已解决。非常感谢您的帮助和付出！
